# Generated by Django 5.2 on 2025-05-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=50)),
                ('seating_capacity', models.PositiveIntegerField()),
                ('transmission', models.CharField(max_length=20)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image_url', models.URLField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
