# Generated by Django 5.2 on 2025-05-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='extra_km_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='car',
            name='free_kms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='is_unlimited_kms',
            field=models.BooleanField(default=False),
        ),
    ]
