# Generated by Django 5.2 on 2025-05-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0002_car_extra_km_charge_car_free_kms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='is_unlimited_kms',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_per_day',
        ),
        migrations.AddField(
            model_name='car',
            name='free_km_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='car',
            name='unlimited_km_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
