# Generated by Django 5.2 on 2025-05-26 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0006_remove_booking_created_at_remove_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='is_available',
        ),
    ]
