# Generated by Django 5.2 on 2025-05-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0007_remove_car_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('ev', 'Electric Vehicle'), ('cng', 'CNG')], default='petrol', max_length=10),
        ),
    ]
