# Generated by Django 5.2 on 2025-05-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0008_car_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price_100km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='car',
            name='price_200km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='car',
            name='price_300km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='car',
            name='price_400km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
