# Generated by Django 5.2 on 2025-05-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0009_car_price_100km_car_price_200km_car_price_300km_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='price_400km',
        ),
        migrations.AddField(
            model_name='car',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
