# Generated by Django 5.2 on 2025-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0012_booking_is_approved_booking_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/aadhar/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='driving_license',
            field=models.FileField(blank=True, null=True, upload_to='documents/license/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/pan/'),
        ),
    ]
