# Generated by Django 5.2 on 2025-06-14 06:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0013_booking_aadhar_card_booking_driving_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='approval_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
