# Generated by Django 5.2 on 2025-06-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0014_booking_approval_token_alter_booking_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='aadhar_card',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='driving_license',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pan_card',
        ),
        migrations.AddField(
            model_name='booking',
            name='dropoff_by_customer',
            field=models.BooleanField(default=True, help_text='Will the customer drop off the car?'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_by_customer',
            field=models.BooleanField(default=True, help_text='Will the customer pick up the car?'),
        ),
    ]
