# Generated by Django 5.2.1 on 2025-06-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0015_remove_booking_aadhar_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
