# Generated by Django 5.2 on 2025-06-18 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0016_booking_full_name_booking_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='price_100km',
            new_name='price_150km',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_200km',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price_300km',
        ),
    ]
