# Generated by Django 5.2 on 2025-06-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0017_rename_price_100km_car_price_150km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('ev', 'Electric Vehicle'), ('cng', 'CNG'), ('petrol_cng', 'Petrol/CNG')], default='petrol', max_length=10),
        ),
    ]
