# Generated by Django 5.2.3 on 2025-06-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0018_alter_car_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='extra_hour_charge_unlimited',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Extra hour charge if unlimited km plan is selected', max_digits=6),
        ),
    ]
