# Generated by Django 5.2.3 on 2025-06-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0019_car_extra_hour_charge_unlimited'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='extra_km_per_hour_150km',
            field=models.PositiveIntegerField(default=0, help_text='Per extra hour after 12 hours, these kms will be charged at extra km rate'),
        ),
    ]
