# Generated by Django 5.2.3 on 2025-07-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0020_car_extra_km_per_hour_150km'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='kms_plan',
            field=models.CharField(choices=[('150km', '150 km'), ('unlimited', 'Unlimited')], default='150km', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='extra_km_per_hour_150km',
            field=models.PositiveIntegerField(default=0, help_text='After 12 hours, extra km given per hour in 150km plan'),
        ),
    ]
