# Generated by Django 5.2.3 on 2025-07-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0021_booking_kms_plan_alter_car_extra_km_per_hour_150km'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='kms_plan',
        ),
    ]
