# Generated by Django 5.2.3 on 2025-07-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0022_remove_booking_kms_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='kms_plan',
            field=models.CharField(choices=[('150km', '150 km'), ('unlimited', 'Unlimited')], default='150km', max_length=20),
        ),
    ]
