# Generated by Django 5.2.3 on 2025-07-03 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0023_booking_kms_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='kms_plan',
        ),
    ]
